yarnPath: .yarn/releases/yarn-3.3.1.cjs
packageExtensions:
  eslint-config-next@*:
    dependencies:
      next: "*"
  prettier@*:
    dependencies:
      "@trivago/prettier-plugin-sort-imports": "*"
      "prettier-plugin-packagejson": "*"
  debug@*:
    dependencies:
      supports-color: "8"
